"""Add tables

Revision ID: 2a9e00b8cee6
Revises: 
Create Date: 2023-07-05 11:27:04.882876

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '2a9e00b8cee6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.VARCHAR(length=320), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('email', name=op.f('uq__users__email'))
    )
    op.create_table('posts',
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk__posts__author_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__posts'))
    )
    op.create_index(op.f('ix__posts__dt_created'), 'posts', ['dt_created'], unique=False)
    op.create_table('likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk__likes__post_id__posts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__likes__user_id__users')),
    sa.PrimaryKeyConstraint('post_id', 'user_id', name=op.f('pk__likes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_index(op.f('ix__posts__dt_created'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
