from models import Post, PostLike, User


# Добавьте сюда таблицы для отслеживания и генерации миграций для них
autogenerated_tables = (Post, PostLike, User)


__all__ = (
    "autogenerated_tables",
)
